services:
  postgres:
    image: postgres:14.6
    container_name: account_book_app_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DEVELOPMENT_DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DEVELOPMENT_DATABASE_PASSWORD}
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
  app:
    build: .
    # tmp/pids/server.pidが残ってたら `A server is already running. ~~` のエラーでrailsを起動できないので事前に消してから、`rails sever` する
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    # 上記のdbイメージで指定したユーザー名とパスワードをrails側でも指定するため環境変数に設定。
    environment:
      - POSTGRES_USER=${DEVELOPMENT_DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DEVELOPMENT_DATABASE_PASSWORD}
    # ホストのカレントディレクトリ(.)とイメージ内の/myappディレクトリを同期させている
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    # 疑似ターミナル (pseudo-TTY) を割り当て。https://docs.docker.jp/compose/compose-file/index.html#tty
    tty: true
    depends_on:
      - postgres
