version: 2.1

orbs:
  ruby: circleci/ruby@1.1.1
  node: circleci/node@4.0.0

jobs:
  build:
    docker:
      - image: cimg/ruby:3.1.3-node
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
    steps:
      - checkout
      - ruby/install-deps:
          bundler-version: 2.3.25
      # - node/install-packages: 
      #     pkg-manager: yarn

  test:
    docker:
      - image: cimg/ruby:3.1.3-node
      - image: circleci/postgres:13.1
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: blog_rails6_test
          POSTGRES_HOST_AUTH_METHOD: trust # パスワードなし
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      PGHOST: 127.0.0.1
      PGUSER: circleci
      PGPASSWORD: ""
      TZ: "/usr/share/zoneinfo/Asia/Tokyo"
      RAILS_ENV: ci_test

    steps:
      - checkout
      - ruby/install-deps:
          bundler-version: 2.3.25
      # - node/install-packages: 
      #     pkg-manager: yarn
      - run:
          name: DB Initializing
          command: |
            dockerize -wait tcp://localhost:5432 -timeout 1m
            bundle exec rake db:create
          # bundle exec rake db:schema:load
      # run tests!
      - run: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
      - run: mkdir ~/reports
      - run:
          command: bundle exec rake test TESTOPTS="--ci-dir=~/reports"
          when: always
      - store_test_results:
          path: ~/reports

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
